<?php

namespace ContainerSvdOpeo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getControladorNegocioService extends Src_Infraestrutura_Kernel_KernelDevDebugContainer
{
    /**
     * Gets the public 'Src\Infraestrutura\Web\Controladores\ControladorNegocio' shared autowired service.
     *
     * @return \Src\Infraestrutura\Web\Controladores\ControladorNegocio
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'Src'.\DIRECTORY_SEPARATOR.'Infraestrutura'.\DIRECTORY_SEPARATOR.'Web'.\DIRECTORY_SEPARATOR.'Controladores'.\DIRECTORY_SEPARATOR.'ControladorNegocio.php';

        return $container->services['Src\\Infraestrutura\\Web\\Controladores\\ControladorNegocio'] = new \Src\Infraestrutura\Web\Controladores\ControladorNegocio(($container->services['Src\\Infraestrutura\\Web\\Servicos\\Handler\\ProcessarNegocioHandler'] ?? $container->load('getProcessarNegocioHandlerService')));
    }
}
