<?php

namespace ContainerQuF8F9B;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProcessarNegocioService extends Src_Infraestrutura_Kernel_KernelDevDebugContainer
{
    /**
     * Gets the public 'Src\Infraestrutura\Web\Servicos\Negocio\ProcessarNegocio' shared autowired service.
     *
     * @return \Src\Infraestrutura\Web\Servicos\Negocio\ProcessarNegocio
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Infraestrutura'.\DIRECTORY_SEPARATOR.'Web'.\DIRECTORY_SEPARATOR.'Servicos'.\DIRECTORY_SEPARATOR.'Negocio'.\DIRECTORY_SEPARATOR.'ProcessarNegocio.php';

        return $container->services['Src\\Infraestrutura\\Web\\Servicos\\Negocio\\ProcessarNegocio'] = new \Src\Infraestrutura\Web\Servicos\Negocio\ProcessarNegocio();
    }
}
