<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQuF8F9B\Src_Infraestrutura_Kernel_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQuF8F9B/Src_Infraestrutura_Kernel_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQuF8F9B.legacy');

    return;
}

if (!\class_exists(Src_Infraestrutura_Kernel_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQuF8F9B\Src_Infraestrutura_Kernel_KernelDevDebugContainer::class, Src_Infraestrutura_Kernel_KernelDevDebugContainer::class, false);
}

return new \ContainerQuF8F9B\Src_Infraestrutura_Kernel_KernelDevDebugContainer([
    'container.build_hash' => 'QuF8F9B',
    'container.build_id' => '5c1f1a2c',
    'container.build_time' => 1733067371,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQuF8F9B');
